/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventDetailsRouteImport } from './routes/event-details'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as ApiPublicFawryCallbackRouteImport } from './routes/api/public/fawry/callback'

const EventDetailsRoute = EventDetailsRouteImport.update({
  id: '/event-details',
  path: '/event-details',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFawryCallbackRoute = ApiPublicFawryCallbackRouteImport.update({
  id: '/api/public/fawry/callback',
  path: '/api/public/fawry/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/event-details': typeof EventDetailsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/booking/$id': typeof BookingIdRoute
  '/packages/$id': typeof PackagesIdRoute
  '/api/public/fawry/callback': typeof ApiPublicFawryCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/event-details': typeof EventDetailsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/booking/$id': typeof BookingIdRoute
  '/packages/$id': typeof PackagesIdRoute
  '/api/public/fawry/callback': typeof ApiPublicFawryCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/event-details': typeof EventDetailsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/booking/$id': typeof BookingIdRoute
  '/packages/$id': typeof PackagesIdRoute
  '/api/public/fawry/callback': typeof ApiPublicFawryCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/event-details'
    | '/activities/$slug'
    | '/booking/$id'
    | '/packages/$id'
    | '/api/public/fawry/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/event-details'
    | '/activities/$slug'
    | '/booking/$id'
    | '/packages/$id'
    | '/api/public/fawry/callback'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/event-details'
    | '/activities/$slug'
    | '/booking/$id'
    | '/packages/$id'
    | '/api/public/fawry/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EventDetailsRoute: typeof EventDetailsRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  BookingIdRoute: typeof BookingIdRoute
  PackagesIdRoute: typeof PackagesIdRoute
  ApiPublicFawryCallbackRoute: typeof ApiPublicFawryCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/event-details': {
      id: '/event-details'
      path: '/event-details'
      fullPath: '/event-details'
      preLoaderRoute: typeof EventDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fawry/callback': {
      id: '/api/public/fawry/callback'
      path: '/api/public/fawry/callback'
      fullPath: '/api/public/fawry/callback'
      preLoaderRoute: typeof ApiPublicFawryCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EventDetailsRoute: EventDetailsRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  BookingIdRoute: BookingIdRoute,
  PackagesIdRoute: PackagesIdRoute,
  ApiPublicFawryCallbackRoute: ApiPublicFawryCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
